// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<Engine> createEngine({required String dataDir}) =>
    RustLib.instance.api.crateApiCreateEngine(dataDir: dataDir);

Future<String> engineRequest({
  required Engine engine,
  required String method,
  required String path,
  required String query,
  String? body,
}) => RustLib.instance.api.crateApiEngineRequest(
  engine: engine,
  method: method,
  path: path,
  query: query,
  body: body,
);

Future<void> engineSetSession({
  required Engine engine,
  required String userid,
  required String token,
  required String t1,
}) => RustLib.instance.api.crateApiEngineSetSession(
  engine: engine,
  userid: userid,
  token: token,
  t1: t1,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Engine>>
abstract class Engine implements RustOpaqueInterface {}
